### ISSUE TITLE
Add regular options

### ISSUE THREAD

**Issue by MathieuAA** [colameo/jhipster-base#1]
If it's okay with you @colameo I'm gonna open a PR for that later today.

**Comment by MathieuAA** [comment]
By the way, should I provide option names as they appear in a JDL content (the tokens) or the option names in JSON files?

**Comment by MathieuAA** [comment]
BTW, I don't get what `ajv` and `md-table` are, are they NPM packages or regular programs. I don't have them and I need them to generate the MD file.

**Comment by colameo** [comment]
> By the way, should I provide option names as they appear in a JDL content (the tokens) or the option names in JSON files?

The option names in the JDL is what I personally need and btw. I've added an installation section in the readme.

**Comment by colameo** [comment]
btw, this is how it looks now in VS code when hovering over parameters:

<img width="674" alt="Screenshot 2020-04-20 at 20 42 05" src="https://user-images.githubusercontent.com/629760/80275261-6a27a200-86e0-11ea-8c70-8c7bd9e41ff0.png">

and this in Eclipse:

<img width="481" alt="Screenshot 2020-04-25 at 10 49 11" src="https://user-images.githubusercontent.com/629760/80275566-6b59ce80-86e2-11ea-8c5b-b141b502fa2d.png">

So, beside of option names and values, descriptions are quite important to explain to user the usage.

**Comment by MathieuAA** [comment]
That's great! I've had more issues with the installation, there'll be another PR for that. I'm almost done
To make the project usable by JS projects, this project needs be packages as an NPM package. We can move it inside the jhipster org to make it easier
