### ISSUE TITLE
application option 'vuejs' change

### ISSUE THREAD

**Issue by colameo** [colameo/jhipster-base#10]
I found [this change](https://github.com/jhipster/jhipster-core/blob/0b648d22c0e00d2b40b9a79b1ce5d94b727a45a5/test/test_files/application_with_blueprints.jdl#L4)

@MathieuAA

**Comment by MathieuAA** [comment]
Ah yes.
The "generator-jhipster" prefix is how one recognizes a JHipster blueprint. If it isn't included in a JDL file, it's added automatically so that JHipster fetches correctly the associated blueprint/s.

**Comment by colameo** [comment]
I'm ready to use this project as a base now. What do you think about including these option tables in the official JDL documentation page?

**Comment by MathieuAA** [comment]
Ready when you are.
How do you think we should proceed with the generator + JCore merge regarding this project?
My plan was to:
  - create a PR with the merge, no refactoring, no change.
  - create more PRs to integrate the merged two parts
  - refactor the unified code base to use this repo

**Comment by colameo** [comment]
About this change, the JDL option (vuejs) has no prefix right? If so we need to remove the prefix from the json model file.

**Comment by MathieuAA** [comment]
Ah no! In JCore, the two are equivalent: if you don't have the prefix, JCore will add it for you. The correct full name is `generator-jhipster-vuejs`, but if JCore parses a JDL file without the prefix, it will output is as `generator-jhipster-vuejs`. https://github.com/jhipster/jhipster-core/commit/0b648d22c0e00d2b40b9a79b1ce5d94b727a45a5#diff-9999cbd16ee32b4c0227805e12916ab3R131
