### ISSUE TITLE
Missing option values

### ISSUE THREAD

**Issue by colameo** [colameo/jhipster-base#12]
Differences of option values ​​in jcore [application_options.js](https://github.com/jhipster/jhipster-core/blob/master/lib/core/jhipster/application_options.js#L182):
- [clientFramework](https://github.com/jhipster/jhipster-core/blob/0b648d22c0e00d2b40b9a79b1ce5d94b727a45a5/lib/core/jhipster/application_options.js#L124) missing [`react`, `vuejs`]
- [databaseType](https://github.com/jhipster/jhipster-core/blob/0b648d22c0e00d2b40b9a79b1ce5d94b727a45a5/lib/core/jhipster/application_options.js#L137) missing [`neo4j`]
- [searchEngine](https://github.com/jhipster/jhipster-core/blob/0b648d22c0e00d2b40b9a79b1ce5d94b727a45a5/lib/core/jhipster/application_options.js#L182) missing [`couchbase`]

cc @MathieuAA do u agree or are they not needed?

**Comment by MathieuAA** [comment]
Everything except vuejs should be added. Vuejs has been added as a temporary fix.
