### ISSUE TITLE
Move this repo to jhipster organisation

### ISSUE THREAD

**Issue by colameo** [colameo/jhipster-base#3]
As soon it's stable, we should move this repository to the jhipster organisation.

**Comment by jdubois** [comment]
@colameo I'm trying to do this right now, hang tight :-)

**Comment by jdubois** [comment]
@colameo sorry I still can't do it, I don't have access to the "settings" tab. Could you try to transfer the repo ownership to myself "jdubois"? I'll then be the owner and be able to transfer it to the JHipster org (which I also own, so I'll have the rights everywhere).

**Comment by colameo** [comment]
btw, don't know if the name of this repo is really appropriated... maybe something like jhipster-shared-data or so would be better?

**Comment by jdubois** [comment]
Migration is complete :-)
For the name it's indeed probably too generic, it doesn't tell what it does. Could you send a few ideas to the mailing list? That would be better than just the 2 of us.

**Comment by colameo** [comment]
will do, and I guess we need also to explain the purpose of this repo a bit better.
